import { Transaction, AIInsight } from './supabase';

export const mockTransactions: Transaction[] = [
  {
    id: '1',
    user_id: 'mock',
    type: 'pix_in',
    amount: 2500.00,
    description: 'Salary',
    category: 'income',
    recipient: 'Company XYZ',
    status: 'completed',
    created_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '2',
    user_id: 'mock',
    type: 'card_purchase',
    amount: -89.90,
    description: 'Restaurant',
    category: 'food',
    recipient: 'Italian Bistro',
    status: 'completed',
    created_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '3',
    user_id: 'mock',
    type: 'payment',
    amount: -150.00,
    description: 'Internet Bill',
    category: 'bills',
    recipient: 'ISP Provider',
    status: 'completed',
    created_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '4',
    user_id: 'mock',
    type: 'card_purchase',
    amount: -45.50,
    description: 'Uber',
    category: 'transport',
    recipient: 'Uber',
    status: 'completed',
    created_at: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '5',
    user_id: 'mock',
    type: 'pix_out',
    amount: -200.00,
    description: 'Transfer to Friend',
    category: 'transfer',
    recipient: 'João Silva',
    status: 'completed',
    created_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '6',
    user_id: 'mock',
    type: 'card_purchase',
    amount: -120.00,
    description: 'Grocery Shopping',
    category: 'shopping',
    recipient: 'Supermarket',
    status: 'completed',
    created_at: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
  },
];

export const mockInsights: AIInsight[] = [
  {
    id: '1',
    user_id: 'mock',
    type: 'tip',
    title: 'Save R$ 420/month',
    message: 'You can save R$ 420 per month by optimizing these 3 spending categories: food delivery, entertainment subscriptions, and impulse shopping.',
    action_label: 'View Details',
    action_data: { category: 'savings' },
    is_read: false,
    created_at: new Date().toISOString(),
  },
  {
    id: '2',
    user_id: 'mock',
    type: 'achievement',
    title: 'Great progress!',
    message: 'You spent 15% less this month compared to last month. Keep it up!',
    action_label: null,
    action_data: null,
    is_read: false,
    created_at: new Date().toISOString(),
  },
  {
    id: '3',
    user_id: 'mock',
    type: 'opportunity',
    title: 'Investment opportunity',
    message: 'Based on your profile, you have R$ 500 that could be invested. Start with low-risk options.',
    action_label: 'Explore',
    action_data: { type: 'investment' },
    is_read: false,
    created_at: new Date().toISOString(),
  },
];

export const categoryColors: Record<string, string> = {
  income: 'text-green-400',
  food: 'text-orange-400',
  transport: 'text-blue-400',
  bills: 'text-red-400',
  shopping: 'text-purple-400',
  transfer: 'text-cyan-400',
  other: 'text-gray-400',
};

export const categoryIcons: Record<string, string> = {
  income: '💰',
  food: '🍽️',
  transport: '🚗',
  bills: '📄',
  shopping: '🛍️',
  transfer: '💸',
  other: '📦',
};
